export interface SeedQuestion {
  difficulty: number;
  prompt: string;
  choices: { id: string; text: string }[];
  correctAnswer: string;
  tags: string[];
}

export const questionsSeed: SeedQuestion[] = [
  // Difficulty 1
  { difficulty: 1, prompt: "What is 2 + 3?", choices: [ { id: "A", text: "5" }, { id: "B", text: "4" }, { id: "C", text: "6" }, { id: "D", text: "7" } ], correctAnswer: "A", tags: ["math", "arithmetic"] },
  { difficulty: 1, prompt: "Which planet is known as the Red Planet?", choices: [ { id: "A", text: "Mars" }, { id: "B", text: "Venus" }, { id: "C", text: "Jupiter" }, { id: "D", text: "Saturn" } ], correctAnswer: "A", tags: ["general", "space"] },
  { difficulty: 1, prompt: "What is the color of a clear daytime sky?", choices: [ { id: "A", text: "Blue" }, { id: "B", text: "Green" }, { id: "C", text: "Red" }, { id: "D", text: "Yellow" } ], correctAnswer: "A", tags: ["general", "science"] },
  { difficulty: 1, prompt: "Which number is even?", choices: [ { id: "A", text: "4" }, { id: "B", text: "7" }, { id: "C", text: "9" }, { id: "D", text: "13" } ], correctAnswer: "A", tags: ["math"] },
  { difficulty: 1, prompt: "What does CPU stand for?", choices: [ { id: "A", text: "Central Processing Unit" }, { id: "B", text: "Central Print Unit" }, { id: "C", text: "Computer Primary Unit" }, { id: "D", text: "Control Program Utility" } ], correctAnswer: "A", tags: ["cs", "basics"] },
  { difficulty: 1, prompt: "Which is a primary color?", choices: [ { id: "A", text: "Red" }, { id: "B", text: "Green" }, { id: "C", text: "Brown" }, { id: "D", text: "Pink" } ], correctAnswer: "A", tags: ["general", "art"] },
  { difficulty: 1, prompt: "How many days are in a week?", choices: [ { id: "A", text: "7" }, { id: "B", text: "5" }, { id: "C", text: "8" }, { id: "D", text: "6" } ], correctAnswer: "A", tags: ["general"] },
  { difficulty: 1, prompt: "Which shape has three sides?", choices: [ { id: "A", text: "Triangle" }, { id: "B", text: "Square" }, { id: "C", text: "Pentagon" }, { id: "D", text: "Circle" } ], correctAnswer: "A", tags: ["math", "geometry"] },
  { difficulty: 1, prompt: "What is 10 - 4?", choices: [ { id: "A", text: "6" }, { id: "B", text: "5" }, { id: "C", text: "4" }, { id: "D", text: "7" } ], correctAnswer: "A", tags: ["math", "arithmetic"] },
  { difficulty: 1, prompt: "Which animal is known for saying 'meow'?", choices: [ { id: "A", text: "Cat" }, { id: "B", text: "Dog" }, { id: "C", text: "Cow" }, { id: "D", text: "Horse" } ], correctAnswer: "A", tags: ["general", "animals"] },

  // Difficulty 2
  { difficulty: 2, prompt: "What is 12 / 3?", choices: [ { id: "A", text: "4" }, { id: "B", text: "3" }, { id: "C", text: "6" }, { id: "D", text: "9" } ], correctAnswer: "A", tags: ["math", "arithmetic"] },
  { difficulty: 2, prompt: "Which data type stores true/false in most languages?", choices: [ { id: "A", text: "Boolean" }, { id: "B", text: "Integer" }, { id: "C", text: "String" }, { id: "D", text: "Array" } ], correctAnswer: "A", tags: ["cs", "basics"] },
  { difficulty: 2, prompt: "What is the capital of France?", choices: [ { id: "A", text: "Paris" }, { id: "B", text: "Berlin" }, { id: "C", text: "Madrid" }, { id: "D", text: "Lisbon" } ], correctAnswer: "A", tags: ["general", "geography"] },
  { difficulty: 2, prompt: "Which unit measures electrical resistance?", choices: [ { id: "A", text: "Ohm" }, { id: "B", text: "Volt" }, { id: "C", text: "Ampere" }, { id: "D", text: "Watt" } ], correctAnswer: "A", tags: ["science", "physics"] },
  { difficulty: 2, prompt: "What is 5 squared?", choices: [ { id: "A", text: "25" }, { id: "B", text: "20" }, { id: "C", text: "15" }, { id: "D", text: "30" } ], correctAnswer: "A", tags: ["math", "arithmetic"] },
  { difficulty: 2, prompt: "Which keyword declares a constant in JavaScript?", choices: [ { id: "A", text: "const" }, { id: "B", text: "var" }, { id: "C", text: "let" }, { id: "D", text: "static" } ], correctAnswer: "A", tags: ["cs", "javascript"] },
  { difficulty: 2, prompt: "Binary of decimal 2 is?", choices: [ { id: "A", text: "10" }, { id: "B", text: "11" }, { id: "C", text: "01" }, { id: "D", text: "100" } ], correctAnswer: "A", tags: ["cs", "binary"] },
  { difficulty: 2, prompt: "What is 15 % 4 (modulo)?", choices: [ { id: "A", text: "3" }, { id: "B", text: "4" }, { id: "C", text: "2" }, { id: "D", text: "1" } ], correctAnswer: "A", tags: ["math", "modulo"] },
  { difficulty: 2, prompt: "Which loop runs at least once in many languages?", choices: [ { id: "A", text: "do-while" }, { id: "B", text: "for" }, { id: "C", text: "while" }, { id: "D", text: "foreach" } ], correctAnswer: "A", tags: ["cs", "control-flow"] },
  { difficulty: 2, prompt: "What does HTML stand for?", choices: [ { id: "A", text: "HyperText Markup Language" }, { id: "B", text: "Hyperlink Text Module Language" }, { id: "C", text: "Home Tool Markup Language" }, { id: "D", text: "Hyper Tabular Markup Language" } ], correctAnswer: "A", tags: ["web", "html"] },

  // Difficulty 3
  { difficulty: 3, prompt: "What is 13 * 4?", choices: [ { id: "A", text: "52" }, { id: "B", text: "48" }, { id: "C", text: "56" }, { id: "D", text: "46" } ], correctAnswer: "A", tags: ["math"] },
  { difficulty: 3, prompt: "Which data structure is LIFO?", choices: [ { id: "A", text: "Stack" }, { id: "B", text: "Queue" }, { id: "C", text: "Array" }, { id: "D", text: "Graph" } ], correctAnswer: "A", tags: ["cs", "ds"] },
  { difficulty: 3, prompt: "Time complexity of binary search?", choices: [ { id: "A", text: "O(log n)" }, { id: "B", text: "O(n)" }, { id: "C", text: "O(n log n)" }, { id: "D", text: "O(1)" } ], correctAnswer: "A", tags: ["cs", "complexity"] },
  { difficulty: 3, prompt: "What is 2^5?", choices: [ { id: "A", text: "32" }, { id: "B", text: "16" }, { id: "C", text: "64" }, { id: "D", text: "48" } ], correctAnswer: "A", tags: ["math", "powers"] },
  { difficulty: 3, prompt: "Which traversal visits node-left-right in a BST?", choices: [ { id: "A", text: "Preorder" }, { id: "B", text: "Inorder" }, { id: "C", text: "Postorder" }, { id: "D", text: "Level order" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 3, prompt: "What is the GCD of 24 and 18?", choices: [ { id: "A", text: "6" }, { id: "B", text: "3" }, { id: "C", text: "12" }, { id: "D", text: "9" } ], correctAnswer: "A", tags: ["math", "number-theory"] },
  { difficulty: 3, prompt: "Which sorting algorithm is stable?", choices: [ { id: "A", text: "Merge sort" }, { id: "B", text: "Selection sort" }, { id: "C", text: "Heap sort" }, { id: "D", text: "Quick sort (naive)" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 3, prompt: "What does OOP stand for?", choices: [ { id: "A", text: "Object-Oriented Programming" }, { id: "B", text: "Object-Operation Process" }, { id: "C", text: "Open Object Protocol" }, { id: "D", text: "Ordered Object Procedure" } ], correctAnswer: "A", tags: ["cs", "oop"] },
  { difficulty: 3, prompt: "Which SQL clause filters rows?", choices: [ { id: "A", text: "WHERE" }, { id: "B", text: "GROUP BY" }, { id: "C", text: "ORDER BY" }, { id: "D", text: "LIMIT" } ], correctAnswer: "A", tags: ["db", "sql"] },
  { difficulty: 3, prompt: "Which notation describes worst-case complexity?", choices: [ { id: "A", text: "Big O" }, { id: "B", text: "Theta" }, { id: "C", text: "Omega" }, { id: "D", text: "Sigma" } ], correctAnswer: "A", tags: ["cs", "complexity"] },

  // Difficulty 4
  { difficulty: 4, prompt: "Solve for x: 3x + 5 = 20", choices: [ { id: "A", text: "5" }, { id: "B", text: "4" }, { id: "C", text: "3" }, { id: "D", text: "6" } ], correctAnswer: "A", tags: ["math", "algebra"] },
  { difficulty: 4, prompt: "Which DS gives O(1) average search?", choices: [ { id: "A", text: "Hash table" }, { id: "B", text: "Array" }, { id: "C", text: "Linked list" }, { id: "D", text: "Binary tree" } ], correctAnswer: "A", tags: ["cs", "ds"] },
  { difficulty: 4, prompt: "Time complexity of merge sort?", choices: [ { id: "A", text: "O(n log n)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n)" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 4, prompt: "Which graph traversal uses a queue?", choices: [ { id: "A", text: "BFS" }, { id: "B", text: "DFS" }, { id: "C", text: "Inorder" }, { id: "D", text: "Preorder" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 4, prompt: "What is the derivative of x^2?", choices: [ { id: "A", text: "2x" }, { id: "B", text: "x" }, { id: "C", text: "x^2" }, { id: "D", text: "1" } ], correctAnswer: "A", tags: ["math", "calculus"] },
  { difficulty: 4, prompt: "Which HTTP method is idempotent?", choices: [ { id: "A", text: "PUT" }, { id: "B", text: "POST" }, { id: "C", text: "PATCH" }, { id: "D", text: "CONNECT" } ], correctAnswer: "A", tags: ["web", "http"] },
  { difficulty: 4, prompt: "Which data structure supports FIFO?", choices: [ { id: "A", text: "Queue" }, { id: "B", text: "Stack" }, { id: "C", text: "Set" }, { id: "D", text: "Trie" } ], correctAnswer: "A", tags: ["cs", "ds"] },
  { difficulty: 4, prompt: "What is the angle sum of a triangle?", choices: [ { id: "A", text: "180 degrees" }, { id: "B", text: "90 degrees" }, { id: "C", text: "270 degrees" }, { id: "D", text: "360 degrees" } ], correctAnswer: "A", tags: ["math", "geometry"] },
  { difficulty: 4, prompt: "Which operation is O(1) in a min-heap?", choices: [ { id: "A", text: "Find min" }, { id: "B", text: "Insert" }, { id: "C", text: "Delete arbitrary" }, { id: "D", text: "Search by value" } ], correctAnswer: "A", tags: ["cs", "heap"] },
  { difficulty: 4, prompt: "Which numeral system is base-16?", choices: [ { id: "A", text: "Hexadecimal" }, { id: "B", text: "Octal" }, { id: "C", text: "Decimal" }, { id: "D", text: "Binary" } ], correctAnswer: "A", tags: ["cs", "number-systems"] },

  // Difficulty 5
  { difficulty: 5, prompt: "Which algorithm finds shortest path in weighted DAG?", choices: [ { id: "A", text: "Topological DP" }, { id: "B", text: "Dijkstra with heap" }, { id: "C", text: "BFS" }, { id: "D", text: "Bellman-Ford full" } ], correctAnswer: "A", tags: ["cs", "graphs", "dp"] },
  { difficulty: 5, prompt: "Time complexity of building a heap of n elements?", choices: [ { id: "A", text: "O(n)" }, { id: "B", text: "O(n log n)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n^2)" } ], correctAnswer: "A", tags: ["cs", "heap"] },
  { difficulty: 5, prompt: "What is the inverse function of ln(x)?", choices: [ { id: "A", text: "e^x" }, { id: "B", text: "log10(x)" }, { id: "C", text: "x^2" }, { id: "D", text: "1/x" } ], correctAnswer: "A", tags: ["math", "calculus"] },
  { difficulty: 5, prompt: "Which data structure best supports prefix queries?", choices: [ { id: "A", text: "Trie" }, { id: "B", text: "Stack" }, { id: "C", text: "Queue" }, { id: "D", text: "Array" } ], correctAnswer: "A", tags: ["cs", "strings"] },
  { difficulty: 5, prompt: "Stability of quicksort depends on?", choices: [ { id: "A", text: "Partition implementation" }, { id: "B", text: "Pivot selection" }, { id: "C", text: "Recursion depth" }, { id: "D", text: "In-place swap" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 5, prompt: "Which operation amortizes to O(1) in dynamic array?", choices: [ { id: "A", text: "Append" }, { id: "B", text: "Insert middle" }, { id: "C", text: "Delete middle" }, { id: "D", text: "Sort" } ], correctAnswer: "A", tags: ["cs", "arrays"] },
  { difficulty: 5, prompt: "What is the determinant of [[1,2],[3,4]]?", choices: [ { id: "A", text: "-2" }, { id: "B", text: "2" }, { id: "C", text: "1" }, { id: "D", text: "-1" } ], correctAnswer: "A", tags: ["math", "linear-algebra"] },
  { difficulty: 5, prompt: "Which algorithm detects cycle in undirected graph?", choices: [ { id: "A", text: "Union-Find" }, { id: "B", text: "Topo sort" }, { id: "C", text: "Dijkstra" }, { id: "D", text: "Prim" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 5, prompt: "What is the expected complexity of quicksort?", choices: [ { id: "A", text: "O(n log n)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n)" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 5, prompt: "Which traversal gives sorted order in BST?", choices: [ { id: "A", text: "Inorder" }, { id: "B", text: "Preorder" }, { id: "C", text: "Postorder" }, { id: "D", text: "Level order" } ], correctAnswer: "A", tags: ["cs", "trees"] },

  // Difficulty 6
  { difficulty: 6, prompt: "Which algorithm finds strongly connected components?", choices: [ { id: "A", text: "Kosaraju" }, { id: "B", text: "Prim" }, { id: "C", text: "Kruskal" }, { id: "D", text: "Dijkstra" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 6, prompt: "Time complexity of BFS on V vertices, E edges?", choices: [ { id: "A", text: "O(V + E)" }, { id: "B", text: "O(V^2)" }, { id: "C", text: "O(E log V)" }, { id: "D", text: "O(log V)" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 6, prompt: "What does dynamic programming trade for speed?", choices: [ { id: "A", text: "Memory" }, { id: "B", text: "Precision" }, { id: "C", text: "Parallelism" }, { id: "D", text: "Recursion" } ], correctAnswer: "A", tags: ["cs", "dp"] },
  { difficulty: 6, prompt: "When is Bellman-Ford preferred over Dijkstra?", choices: [ { id: "A", text: "Negative edges" }, { id: "B", text: "No edges" }, { id: "C", text: "Complete graph" }, { id: "D", text: "Tree" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 6, prompt: "What is the characteristic of a stable sort?", choices: [ { id: "A", text: "Preserves equal keys order" }, { id: "B", text: "Uses extra memory" }, { id: "C", text: "Always O(n log n)" }, { id: "D", text: "In-place" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 6, prompt: "Which recurrence solves to O(n log n)?", choices: [ { id: "A", text: "T(n)=2T(n/2)+n" }, { id: "B", text: "T(n)=T(n-1)+1" }, { id: "C", text: "T(n)=T(n/2)+1" }, { id: "D", text: "T(n)=3T(n/3)+n^2" } ], correctAnswer: "A", tags: ["cs", "recurrence"] },
  { difficulty: 6, prompt: "What is the Jacobian used for?", choices: [ { id: "A", text: "Transformations and gradients" }, { id: "B", text: "Sorting" }, { id: "C", text: "Graph search" }, { id: "D", text: "Hashing" } ], correctAnswer: "A", tags: ["math", "calculus"] },
  { difficulty: 6, prompt: "Which algorithm finds MST with greedy edges?", choices: [ { id: "A", text: "Kruskal" }, { id: "B", text: "Floyd-Warshall" }, { id: "C", text: "Bellman-Ford" }, { id: "D", text: "Johnson" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 6, prompt: "What is tail recursion optimization for?", choices: [ { id: "A", text: "Reuse stack frames" }, { id: "B", text: "Parallelize loops" }, { id: "C", text: "Cache results" }, { id: "D", text: "Generate code" } ], correctAnswer: "A", tags: ["cs", "recursion"] },
  { difficulty: 6, prompt: "What is the complexity of heapify of one node?", choices: [ { id: "A", text: "O(log n)" }, { id: "B", text: "O(1)" }, { id: "C", text: "O(n)" }, { id: "D", text: "O(n log n)" } ], correctAnswer: "A", tags: ["cs", "heap"] },

  // Difficulty 7
  { difficulty: 7, prompt: "Which algorithm finds all-pairs shortest paths with negative edges (no negative cycles)?", choices: [ { id: "A", text: "Floyd-Warshall" }, { id: "B", text: "Dijkstra" }, { id: "C", text: "Prim" }, { id: "D", text: "Kruskal" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 7, prompt: "What is the complexity of naive matrix multiplication (n x n)?", choices: [ { id: "A", text: "O(n^3)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(n log n)" }, { id: "D", text: "O(log n)" } ], correctAnswer: "A", tags: ["math", "algebra"] },
  { difficulty: 7, prompt: "Which data structure can implement LRU cache efficiently?", choices: [ { id: "A", text: "Hash map + doubly linked list" }, { id: "B", text: "Queue" }, { id: "C", text: "Stack" }, { id: "D", text: "Trie" } ], correctAnswer: "A", tags: ["cs", "design"] },
  { difficulty: 7, prompt: "Master theorem: T(n)=3T(n/2)+n^2 gives?", choices: [ { id: "A", text: "O(n^2 log n)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(n^{log_2 3})" }, { id: "D", text: "O(n^3)" } ], correctAnswer: "A", tags: ["cs", "recurrence"] },
  { difficulty: 7, prompt: "What is the worst-case of quickselect?", choices: [ { id: "A", text: "O(n^2)" }, { id: "B", text: "O(n log n)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n)" } ], correctAnswer: "A", tags: ["cs", "selection"] },
  { difficulty: 7, prompt: "Which algorithm detects negative cycles?", choices: [ { id: "A", text: "Bellman-Ford" }, { id: "B", text: "Dijkstra" }, { id: "C", text: "Prim" }, { id: "D", text: "Kruskal" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 7, prompt: "What is the determinant used for in linear algebra?", choices: [ { id: "A", text: "Testing invertibility" }, { id: "B", text: "Sorting arrays" }, { id: "C", text: "Hashing data" }, { id: "D", text: "Network routing" } ], correctAnswer: "A", tags: ["math", "linear-algebra"] },
  { difficulty: 7, prompt: "Which structure supports range minimum query with O(1) after O(n log n) build?", choices: [ { id: "A", text: "Sparse Table" }, { id: "B", text: "Segment Tree" }, { id: "C", text: "Fenwick Tree" }, { id: "D", text: "Queue" } ], correctAnswer: "A", tags: ["cs", "rmq"] },
  { difficulty: 7, prompt: "What is the amortized cost of splaying in splay trees?", choices: [ { id: "A", text: "O(log n)" }, { id: "B", text: "O(1)" }, { id: "C", text: "O(n)" }, { id: "D", text: "O(log log n)" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 7, prompt: "What is the purpose of memoization?", choices: [ { id: "A", text: "Cache expensive function calls" }, { id: "B", text: "Encrypt data" }, { id: "C", text: "Sort arrays" }, { id: "D", text: "Manage threads" } ], correctAnswer: "A", tags: ["cs", "dp"] },

  // Difficulty 8
  { difficulty: 8, prompt: "Which algorithm computes convex hull in O(n log n)?", choices: [ { id: "A", text: "Graham scan" }, { id: "B", text: "DFS" }, { id: "C", text: "Prim" }, { id: "D", text: "Bellman-Ford" } ], correctAnswer: "A", tags: ["cs", "geometry"] },
  { difficulty: 8, prompt: "What is the complexity of Strassen's matrix multiply?", choices: [ { id: "A", text: "O(n^{log_2 7})" }, { id: "B", text: "O(n^3)" }, { id: "C", text: "O(n^2)" }, { id: "D", text: "O(n^{2.5})" } ], correctAnswer: "A", tags: ["cs", "algebra"] },
  { difficulty: 8, prompt: "Which algorithm solves LIS in O(n log n)?", choices: [ { id: "A", text: "Patience sorting" }, { id: "B", text: "DFS" }, { id: "C", text: "Naive DP" }, { id: "D", text: "Counting sort" } ], correctAnswer: "A", tags: ["cs", "dp"] },
  { difficulty: 8, prompt: "What is the diameter of a tree computed with?", choices: [ { id: "A", text: "Double BFS/DFS" }, { id: "B", text: "Single DFS" }, { id: "C", text: "Topo sort" }, { id: "D", text: "Union-Find" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 8, prompt: "Which data structure supports order statistics in O(log n)?", choices: [ { id: "A", text: "Balanced BST with sizes" }, { id: "B", text: "Queue" }, { id: "C", text: "Stack" }, { id: "D", text: "Trie" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 8, prompt: "Which algorithm converts NFA to DFA?", choices: [ { id: "A", text: "Subset construction" }, { id: "B", text: "Aho-Corasick" }, { id: "C", text: "KMP" }, { id: "D", text: "Tarjan" } ], correctAnswer: "A", tags: ["cs", "automata"] },
  { difficulty: 8, prompt: "What is the complexity of building a suffix array with prefix doubling?", choices: [ { id: "A", text: "O(n log n)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n)" } ], correctAnswer: "A", tags: ["cs", "strings"] },
  { difficulty: 8, prompt: "Which algorithm computes min-cut max-flow in O(V^2 E)?", choices: [ { id: "A", text: "Edmonds-Karp" }, { id: "B", text: "Kruskal" }, { id: "C", text: "Prim" }, { id: "D", text: "Bellman-Ford" } ], correctAnswer: "A", tags: ["cs", "flow"] },
  { difficulty: 8, prompt: "What is the complexity of binary lifting LCA?", choices: [ { id: "A", text: "O(log n) query, O(n log n) build" }, { id: "B", text: "O(1) query, O(n^2) build" }, { id: "C", text: "O(n) query" }, { id: "D", text: "O(log log n) query" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 8, prompt: "Which algorithm finds articulation points?", choices: [ { id: "A", text: "Tarjan DFS" }, { id: "B", text: "BFS" }, { id: "C", text: "Kruskal" }, { id: "D", text: "Dijkstra" } ], correctAnswer: "A", tags: ["cs", "graphs"] },

  // Difficulty 9
  { difficulty: 9, prompt: "What is the time complexity of FFT?", choices: [ { id: "A", text: "O(n log n)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(log n)" }, { id: "D", text: "O(n)" } ], correctAnswer: "A", tags: ["cs", "fft"] },
  { difficulty: 9, prompt: "Which algorithm solves min-cost max-flow with potentials?", choices: [ { id: "A", text: "Successive shortest augmenting path with Johnson" }, { id: "B", text: "Prim" }, { id: "C", text: "Kruskal" }, { id: "D", text: "Kosaraju" } ], correctAnswer: "A", tags: ["cs", "flow"] },
  { difficulty: 9, prompt: "What is the complexity of computing all subsets of an n-set?", choices: [ { id: "A", text: "O(n 2^n)" }, { id: "B", text: "O(2^n)" }, { id: "C", text: "O(n^2)" }, { id: "D", text: "O(n!)" } ], correctAnswer: "A", tags: ["cs", "combinatorics"] },
  { difficulty: 9, prompt: "Which algorithm answers RMQ in O(1) with O(n) build?", choices: [ { id: "A", text: "Cartesian tree + Euler tour + sparse table" }, { id: "B", text: "Segment tree" }, { id: "C", text: "Fenwick tree" }, { id: "D", text: "Binary lifting" } ], correctAnswer: "A", tags: ["cs", "rmq"] },
  { difficulty: 9, prompt: "What is the lower bound for comparison sorting?", choices: [ { id: "A", text: "Ω(n log n)" }, { id: "B", text: "Ω(n)" }, { id: "C", text: "Ω(log n)" }, { id: "D", text: "Ω(n^2)" } ], correctAnswer: "A", tags: ["cs", "sorting"] },
  { difficulty: 9, prompt: "Which algorithm finds max bipartite matching in O(VE)?", choices: [ { id: "A", text: "Hopcroft-Karp" }, { id: "B", text: "Prim" }, { id: "C", text: "Kruskal" }, { id: "D", text: "Dijkstra" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 9, prompt: "What does Karatsuba's algorithm improve?", choices: [ { id: "A", text: "Integer multiplication" }, { id: "B", text: "Sorting" }, { id: "C", text: "Graph traversal" }, { id: "D", text: "String search" } ], correctAnswer: "A", tags: ["cs", "algebra"] },
  { difficulty: 9, prompt: "Which structure supports persistent versions efficiently?", choices: [ { id: "A", text: "Persistent segment tree" }, { id: "B", text: "Queue" }, { id: "C", text: "Stack" }, { id: "D", text: "Array" } ], correctAnswer: "A", tags: ["cs", "persistent"] },
  { difficulty: 9, prompt: "What is the complexity of solving TSP with DP over subsets?", choices: [ { id: "A", text: "O(n^2 2^n)" }, { id: "B", text: "O(n!)" }, { id: "C", text: "O(n 2^n)" }, { id: "D", text: "O(2^n)" } ], correctAnswer: "A", tags: ["cs", "dp"] },
  { difficulty: 9, prompt: "Which algorithm counts inversions in O(n log n)?", choices: [ { id: "A", text: "Merge sort with counts" }, { id: "B", text: "Selection sort" }, { id: "C", text: "Bubble sort" }, { id: "D", text: "Counting sort" } ], correctAnswer: "A", tags: ["cs", "arrays"] },

  // Difficulty 10
  { difficulty: 10, prompt: "What is the complexity of the Hungarian algorithm for assignment?", choices: [ { id: "A", text: "O(n^3)" }, { id: "B", text: "O(n^2)" }, { id: "C", text: "O(n log n)" }, { id: "D", text: "O(2^n)" } ], correctAnswer: "A", tags: ["cs", "optimization"] },
  { difficulty: 10, prompt: "Which algorithm computes min-cut in undirected graphs near-linear time?", choices: [ { id: "A", text: "Karger's randomized contraction" }, { id: "B", text: "Dijkstra" }, { id: "C", text: "Prim" }, { id: "D", text: "DFS" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 10, prompt: "What is the exponent in the best known matrix multiplication (as of 2025)?", choices: [ { id: "A", text: "~2.372" }, { id: "B", text: "3" }, { id: "C", text: "2.1" }, { id: "D", text: "2.5" } ], correctAnswer: "A", tags: ["cs", "algebra"] },
  { difficulty: 10, prompt: "Which algorithm solves max flow in O(E * min(V^{2/3}, E^{1/2})) for unit networks?", choices: [ { id: "A", text: "Dinic with scaling" }, { id: "B", text: "Ford-Fulkerson" }, { id: "C", text: "Kruskal" }, { id: "D", text: "Prim" } ], correctAnswer: "A", tags: ["cs", "flow"] },
  { difficulty: 10, prompt: "Which technique is used in centroid decomposition?", choices: [ { id: "A", text: "Divide and conquer on tree centers" }, { id: "B", text: "Greedy matching" }, { id: "C", text: "Dynamic programming on DAG" }, { id: "D", text: "Random sampling" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 10, prompt: "What is the complexity of Hopcroft-Karp on bipartite graph with V vertices, E edges?", choices: [ { id: "A", text: "O(E * sqrt(V))" }, { id: "B", text: "O(VE)" }, { id: "C", text: "O(V^2)" }, { id: "D", text: "O(E log V)" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 10, prompt: "Which algorithm answers static LCA in O(1) with O(n) build?", choices: [ { id: "A", text: "Euler tour + RMQ with sparse table" }, { id: "B", text: "Binary lifting" }, { id: "C", text: "DFS" }, { id: "D", text: "KMP" } ], correctAnswer: "A", tags: ["cs", "trees"] },
  { difficulty: 10, prompt: "Which technique underlies suffix automaton construction time complexity?", choices: [ { id: "A", text: "Linear-time incremental extension" }, { id: "B", text: "Divide and conquer" }, { id: "C", text: "Matrix exponentiation" }, { id: "D", text: "FFT" } ], correctAnswer: "A", tags: ["cs", "strings"] },
  { difficulty: 10, prompt: "What is the complexity of Johnson's algorithm for all-pairs shortest path with sparse graph?", choices: [ { id: "A", text: "O(VE log V)" }, { id: "B", text: "O(V^3)" }, { id: "C", text: "O(E^2)" }, { id: "D", text: "O(V^2)" } ], correctAnswer: "A", tags: ["cs", "graphs"] },
  { difficulty: 10, prompt: "Which algorithm counts number of perfect matchings in bipartite graphs using determinants?", choices: [ { id: "A", text: "Ryser formula / matrix permanent" }, { id: "B", text: "Dijkstra" }, { id: "C", text: "Prim" }, { id: "D", text: "Kruskal" } ], correctAnswer: "A", tags: ["cs", "combinatorics"] },
];
